services:
  http:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        SERVICE: http
    ports:
      - 8080:8080
    volumes:
      - ./service/http:/app/service/http
      - ./utils:/app/utils
